/**
 * Student Name: Nicholas Morris
 * Student Number: ST10502284
 * Assignment: PROG5121 PoE Part 1 - Registration and Login
 * Description: This class handles the validation logic for for the Main class
 */
package part1;

public class Login {//start of class

    //declare my local variables
    private String username;
    private String password;
    private String cellPhoneNumber;
    private String firstName;
    private String surname;

    /*
     * Checks if the username is correctly formatted
     * @param username the username to check
     * @return true if the username is correctly formatted, false otherwise
     */
    public boolean checkUserName(String username) {

        /* 1. Contains an underscore
           2. Is 5 characters long or less
         */
        //Returns true if conditions are met, returns false otherwise
        return username.contains("_") && username.length() <= 5;
    }

    /*
     * Checks if the password is complex enough
     * @param password the password to check
     * @return true if the password is complex enough, false otherwise
     */
    public boolean checkPasswordComplexity(String password) {

        /*4 conditions need to be checked
          1. Length >= 8
          2. Contains a capital letter
          3. Contains a number
          4. contains a special character
         */
        //I will use a FLAG system to check password complexity
        boolean hasLength = false;
        boolean hasCapital = false;
        boolean hasNum = false;
        boolean hasSpecial = false;

        //If statement checks for password length condition
        if (password.length() >= 8) {
            hasLength = true;
        }

        // for loop that cycles through each character in the password
        for (int i = 0; i < password.length(); i++) {

            //stores the character of the password at position i 
            char c = password.charAt(i);

            //checks and assigns true values to FLAGS if condition is TRUE
            if (Character.isUpperCase(c)) {
                hasCapital = true;
            } else if (Character.isDigit(c)) {
                hasNum = true;
            } else if (!Character.isLetterOrDigit(c)) {
                hasSpecial = true;
            }
        }
        //returns false if all conditions are not met
        return hasLength && hasCapital && hasNum && hasSpecial;
    }

    /*
     * Checks if the cell phone number is correctly formatted
     * @param cellphoneNumber the cell phone number to check
     * @return true if the cell phone number is correctly formatted, false otherwise
     */
    public boolean checkCellPhoneNumber(String cellphoneNumber) {

        // Logic for cell phone validation generated by Gemini 3 Flash (Google AI) 
        // on March 19, 2026. Pattern ensures international code and 10-character limit.
        // Reference: https://apastyle.apa.org/blog/how-to-cite-chatgpt
        //See reference index [1] for more details
        // The pattern: Starts with +27 followed by exactly 9 digits (No more than 10)
        String regex = "^\\+27\\d{9}$"; //(Google Gemini, 2026)

        // Check if the input matches the pattern
        return cellphoneNumber.matches(regex);

    }

    /*
     * Registers a new user if all validation checks pass
     * @param username the username to register
     * @param password the password to register
     * @param firstName the first name of the user
     * @param surname the surname of the user
     * @param cellphoneNumber the cell phone number of the user
     * @return a message indicating the result of the registration attempt
     */
    public String registerUser(String username, String password, String firstName, String surname, String cellphoneNumber) {

        //I am going to make use of a String builder to appened certain error messages with eachother.
        //Create StringBuilder object
        StringBuilder validationsErrBuilder = new StringBuilder();
        if (!checkUserName(username)) {

            //append String to the Stringbuilder object. Since the String is long, I use a String block
            validationsErrBuilder.append("""
                             :>> Username is not correctly formatted, please ensure that your username contains an underscore and is no more that five characters in length <<
                             """);

            //I use individual if statements to check each condition independently and allow for StringBuilder to store each error.
        }
        if (!checkPasswordComplexity(password)) {

            validationsErrBuilder.append("""
                             :>> Password is not correctly formatted, please ensure that the pasword contains at least eight characters , a capital letter, a number, and a special character <<
                             """);
        }
        if (!checkCellPhoneNumber(cellphoneNumber)) {

            validationsErrBuilder.append(":>> Cellphone incorrectly formatted or does not contain international code, please correct the number and try again. <<");

        }
        //Use StringBuilder objects length as condition to check whether or not there were errors
        //>0 means that there were errors
        //=0 means that there were none
        if (validationsErrBuilder.length() > 0) {

            //Converting the StringBuilder object to a String that will be displayed
            return validationsErrBuilder.toString();

            //else we return a successful registration
        } else {

            //Store entered data into local variables
            this.username = username;
            this.password = password;
            this.firstName = firstName;
            this.surname = surname;
            this.cellPhoneNumber = cellphoneNumber;

            //return a message telling the user they have registered successfully
            return "Username, Password, and Cellphone number successfully captured.\nYou have been registered successfully!";
        }
    }

    /*
     * Checks entered username and password to stored values
     * @param enteredUsr the username to check
     * @param enteredPass the password to check
     * @return true if the username and password match, false otherwise
     */
    public boolean loginUser(String enteredUsr, String enteredPass) {

        //checks the entered username and password to the stored version when registered
        //returns true if they match
        //returns false if they do not
        return enteredUsr.equals(this.username) && enteredPass.equals(this.password);
    }

    /*
     * Checks the login status
     * @param isLoggedIn true if the user is logged in, false otherwise
     * @return a message indicating the login status
     */
    public String returnLoginStatus(boolean isLoggedIn) {
        //if boolean argument is true, returns a weclome message
        if (isLoggedIn) {
            return "Welcome " + firstName + " " + surname + ", it is great to see you again.";
            //otherwise, asks the user to try again
        } else {
            return "Username or password incorrect, please try again.";
        }
    }

}//end of class
