/**
 * Student Name: Nicholas Morris
 * Student Number: ST10502284
 * Assignment: PROG5121 PoE Part 1 - Registration and Login
 * Description: This class handles the validation logic for user registration.
 */
package poe.part1.logic;

public class Login {//Class Begin

    //Private variable declaration
    private String username;
    private String password;
    private String cellPhoneNumber;
    private String firstName;
    private String surname;

    //first method, username checker
    public boolean checkUserName(String username) {

        /* 1. Contains an underscore
           2. Is 5 characters long or less
         */
        //Returns true if conditions are met
        return username.contains("_") && username.length() <= 5;
    }

    //second method, password checker
    public boolean checkPasswordComplexity(String password) {

        /*4 conditions need to be checked
          1. Length >= 8
          2. Contains a capital letter
          3. Contains a number
          4. contains a special character
         */
        //I will use a FLAG system to check password complexity
        boolean hasLength = false;
        boolean hasCapital = false;
        boolean hasNum = false;
        boolean hasSpecial = false;

        //checks for password length condition
        if (password.length() >= 8) {
            hasLength = true;
        }

        //assigns the length of the password        
        int length = password.length();

        //cycles through each character 
        for (int i = 0; i < length; i++) {

            //stores the character at position i 
            char c = password.charAt(i);

            //checks and assigns true values to FLAGS if condition is TRUE
            if (Character.isUpperCase(c)) {
                hasCapital = true;
            } else if (Character.isDigit(c)) {
                hasNum = true;
            } else if (!Character.isLetterOrDigit(c)) {
                hasSpecial = true;
            }
        }
        //returns false if all conditions are not met
        return hasLength == true && hasCapital == true && hasNum == true && hasSpecial == true;
    }

    //Third method, cell phone checker
    public boolean checkCellPhoneNumber(String cellphoneNumber) {
        // Logic for cell phone validation generated by Gemini 3 Flash (Google AI) 
        // on March 19, 2026. Pattern ensures international code and 10-character limit.
        // Reference: https://apastyle.apa.org/blog/how-to-cite-chatgpt
        //See reference index [1] for more details

        // The pattern: Starts with +27 followed by exactly 9 digits (No more than 10)
        String regex = "^\\+27\\d{9}$"; //(Google Gemini, 2026)

        // Check if the input matches the pattern
        return cellphoneNumber.matches(regex);

    }

    //Fourth method, displays messages depending on return type. Also stores entered username and password in local variables
    public String registerUser(String username, String password, String fName, String lName, String cellphoneNumber) {

        //I am going to make use of a String builder to appened certain error messages with eachother.
        //Initialise StringBuilder object
        StringBuilder errorBowl = new StringBuilder();
        if (!checkUserName(username)) {

            //append String to the Stringbuilder object
            errorBowl.append(">> Username is not correctly formatted, please ensure that your username contains an underscore "
                    + "and is no more that five characters in length<<\n");

            //Use individual if statements to check each condition independently and allow for StringBuilder to store each error.
        }
        if (!checkPasswordComplexity(password)) {
            errorBowl.append(">>Password is not correctly formatted, please ensure that the pasword contains at least eight characters "
                    + ", a capital letter, a number, and a special character<<\n");

        }
        if (!checkCellPhoneNumber(cellphoneNumber)) {

            errorBowl.append(">>Cellphone incorrectly formatted or does not contain international code, please correct the number and try again.<<");

            //Use StringBuilder object as condition to check wether there were errors or not
            //>0 means that there were errors
        }
        if (errorBowl.length() > 0) {

            //Converting the StringBuilder object to a String that will be displayed
            return errorBowl.toString();

            //else we return a successful registration
        } else {
            //Store entered data into local variables
            this.username = username;
            this.password = password;
            this.firstName = fName;
            this.surname = lName;
            this.cellPhoneNumber = cellphoneNumber;

            //Assign
            return "Username, Password, and Cellphone number successfully captured.\nYou have been registered successfully!";
        }
    }

    //Fifth method, checks entered username and password to stored values
    public boolean loginUser(String enteredUsr, String enteredPass) {
        //checks the entered username and password to the stored version when registered
        return enteredUsr.equals(this.username) && enteredPass.equals(this.password);
    }

    //Sixth method, checks login
    public String returnLoginStatus(boolean isLoggedIn) {
        if (isLoggedIn) {
            return "Welcome " + firstName + " " + surname + ", it is great to see you again.";
        } else {
            return "Username or password incorrect, please try again.";
        }
    }

}
