/**
 * Student Name: Nicholas Morris
 * Student Number: ST10502284
 * Assignment: PROG5121 PoE Part 1 - Registration and Login
 * Description: This class handles the validation logic for user registration.
 */
package poe.part1.logic;

public class Login {
    
    private String username;
    private String password;
    private String cellPhoneNumber;
    private String firstName;
    private String surname;

    public Login(String username, String password, String cellPhoneNumber, String firstName, String surname) {
        this.username = username;
        this.password = password;
        this.cellPhoneNumber = cellPhoneNumber;
        this.firstName = firstName;
        this.surname = surname;
    }
    

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getCellPhoneNumber() {
        return cellPhoneNumber;
    }

    public void setCellPhoneNumber(String cellPhoneNumber) {
        this.cellPhoneNumber = cellPhoneNumber;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }
    
    
    
//first method, username checker
    public boolean checkUserName(String username){
        
    //Returns true if conditions are met
        return username.contains("_") && username.length() <= 5;
    }
    
//second method, password checker
    public boolean checkPasswordComplexity(String password){    
        //4 conditions need to be checked
        // 1. Length >= 8
        // 2. Contains a capital letter
        // 3. Contains a number
        // 4. contains a special character
        
    //I will use a FLAG system to check password complexity
        boolean hasLength = false;
        boolean  hasCapital = false;
        boolean  hasNum = false;
        boolean  hasSpecial = false;
        
        //checks for password length condition
            if(password.length() >= 8){
                hasLength = true;
            }
            
    //assigns the length of the password        
        int length = password.length();
            
        //cycles through each character 
            for (int i = 0; i < length; i++) {
            
            //stores the character at position i 
                char c = password.charAt(i);
                
                //checks and assigns true values to 
                    if(Character.isUpperCase(c)){
                        hasCapital = true;
                    }else if(Character.isDigit(c)){
                        hasNum = true;
                    }else if(!Character.isLetterOrDigit(c)){
                        hasSpecial = true;
                    }    
            }
            
        return hasLength==true && hasCapital==true && hasNum==true && hasSpecial==true; 
    }
    
    //Third method, cell phone checker
    public boolean checkCellPhoneNumber(String cellphoneNumber){
        // Logic for cell phone validation generated by Gemini 3 Flash (Google AI) 
        // on March 19, 2026. Pattern ensures international code and 10-character limit.
        // Reference: https://apastyle.apa.org/blog/how-to-cite-chatgpt
             
        // The pattern: Starts with +27 followed by exactly 9 digits (No more than 10)
        String regex = "^\\+27\\d{9}$"; //(Google Gemini, 2026)
    
    // Check if the input matches the pattern
    return cellphoneNumber.matches(regex);
            
    }
    
    
    //Fourth method, displays messages depending on return type. Also stores entered username and password in local variables
    public String registerUser(String username, String password, String fName, String lName){
        
        if(!checkUserName(username)){
            
            return "Username is not correctly formatted, please ensure that your username contains an underscore " +
                    "and is no more that five characters in length";
        }else if(!checkPasswordComplexity(password)){
            
            return"Password is not correctly formatted, please ensure that the pasword contains at least eight characters " +
                    ", a capital letter, a number, and a special character";
        }else{
            //Store entered data into local variables
            this.username = username;
            this.password = password;
            this.firstName = fName;
            this.surname = lName;
            return "Username and password successfully captured, You have been registered successfully!";
        }
    }
    
   
    
    public boolean loginUser(String enteredUsr, String enteredPass){
        
        //checks the entered username and password to the stored version when registered
    return enteredUsr.equals(this.username) && enteredPass.equals(this.password);
    }
    

}
